name: Deploy cadet-frontend
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to deploy"
        required: true
      env:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - prod
          - stg
        default: stg

jobs:
  deploy:
    name: Deploy cadet-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          path: src

      - name: Checkout deployment configuration
        uses: actions/checkout@v4
        with:
          repository: "NUS-CS1101S/deployment"
          ref: master
          persist-credentials: false
          ssh-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          path: deployment

      - name: Setup Sentry CLI
        run: |
          curl -sL https://sentry.io/get-cli/ | INSTALL_DIR=. bash

      # Has to be run before actions/setup-node.
      # See: https://github.com/actions/setup-node/issues/480
      - name: Enable corepack for Yarn
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: src/yarn.lock
          cache: yarn

      - uses: actions/cache@v4
        id: build-cache
        with:
          path: src/node_modules/.cache
          key: 1-${{ runner.os }}-${{ github.event.inputs.env }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            1-${{ runner.os }}-${{ github.event.inputs.env }}-build-

      - name: Install dependencies
        working-directory: src
        run: JOBS=$(nproc) yarn install --frozen-lockfile

      - name: Build
        working-directory: src
        run: $GITHUB_WORKSPACE/deployment/cadet-frontend/build-frontend.sh ${{ github.event.inputs.env }}

      - name: Create Sentry release
        working-directory: src/build
        run: |
          SENTRY_RELEASE="cadet-frontend@$(cat version.txt)"
          "$GITHUB_WORKSPACE/sentry-cli" releases new -p "$SENTRY_PROJECT" "$SENTRY_RELEASE"
          "$GITHUB_WORKSPACE/sentry-cli" releases set-commits --auto "$SENTRY_RELEASE"
          "$GITHUB_WORKSPACE/sentry-cli" releases files "$SENTRY_RELEASE" upload-sourcemaps --url-prefix '~/static/js' --rewrite static/js
          "$GITHUB_WORKSPACE/sentry-cli" releases finalize "$SENTRY_RELEASE"
          "$GITHUB_WORKSPACE/sentry-cli" releases deploys "$SENTRY_RELEASE" new -e "cs1101s-$INPUT_ENV"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: sourceacademy
          SENTRY_PROJECT: cadet-frontend
          INPUT_ENV: ${{ github.event.inputs.env }}

      - name: Remove source maps
        working-directory: src/build
        run: find -name '*.map' -delete -print

      - name: Deploy
        working-directory: src/build
        run: $GITHUB_WORKSPACE/deployment/cadet-frontend/deploy-frontend.sh ${{ github.event.inputs.env }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
